// Generated by @modern-reservation/port-manager
// DO NOT EDIT MANUALLY - Run: ./dev.sh config-generate

package com.modernreservation.config;

public final class ServicePorts {
    private ServicePorts() {}

    /** Guest Portal UI */
    public static final int GUEST_PORTAL = 3000;

    /** Guest Portal UI (Dev) */
    public static final int GUEST_PORTAL_DEV = 3001;

    /** Admin Portal UI */
    public static final int ADMIN_PORTAL = 3010;

    /** Staff Portal UI */
    public static final int STAFF_PORTAL = 3020;

    /** Spring Cloud Gateway - Main API Entry Point */
    public static final int GATEWAY_SERVICE = 8080;

    /** PgAdmin UI */
    public static final int PGADMIN = 5050;

    /** Kafka UI */
    public static final int KAFKA_UI = 8090;

    /** Eureka Service Discovery UI */
    public static final int EUREKA_SERVER = 8761;

    /** Jaeger UI */
    public static final int JAEGER = 16686;

    /** Authentication Service */
    public static final int AUTH_SERVICE = 3100;

    /** Notification Service */
    public static final int NOTIFICATION_SERVICE = 3110;

    /** WebSocket Service */
    public static final int WEBSOCKET_SERVICE = 3120;

    /** File Upload Service */
    public static final int FILE_UPLOAD_SERVICE = 3130;

    /** Audit Service */
    public static final int AUDIT_SERVICE = 3140;

    /** Channel Manager */
    public static final int CHANNEL_MANAGER = 3150;

    /** Housekeeping Service */
    public static final int HOUSEKEEPING_SERVICE = 3160;

    /** PostgreSQL Database */
    public static final int POSTGRES = 5432;

    /** PostgreSQL Test Database */
    public static final int POSTGRES_TEST = 5433;

    /** Redis Cache */
    public static final int REDIS = 6379;

    /** Redis Cluster */
    public static final int REDIS_CLUSTER = 6380;

    /** Reservation Engine Service */
    public static final int RESERVATION_ENGINE = 8100;

    /** Availability Calculator Service */
    public static final int AVAILABILITY_CALCULATOR = 8110;

    /** Rate Management Service */
    public static final int RATE_MANAGEMENT = 8120;

    /** Payment Processor Service */
    public static final int PAYMENT_PROCESSOR = 8130;

    /** Analytics Engine Service */
    public static final int ANALYTICS_ENGINE = 8140;

    /** Tenant Service */
    public static final int TENANT_SERVICE = 8150;

    /** Spring Cloud Config Server */
    public static final int CONFIG_SERVER = 8888;

    /** Prometheus Metrics */
    public static final int PROMETHEUS = 9090;

    /** Grafana Dashboard */
    public static final int GRAFANA = 3003;

    /** Apache Kafka */
    public static final int KAFKA = 9092;

    /** Kafka External Access */
    public static final int KAFKA_EXTERNAL = 29092;

    /** Kafka Schema Registry */
    public static final int SCHEMA_REGISTRY = 8081;

    /** Zookeeper */
    public static final int ZOOKEEPER = 2181;

    /** OpenTelemetry Collector GRPC */
    public static final int OTEL_COLLECTOR_GRPC = 4317;

    /** OpenTelemetry Collector HTTP */
    public static final int OTEL_COLLECTOR_HTTP = 4318;

}
