# Infrastructure Services - External Dependencies
# These are not part of your application code but required for operation

version: '3.8'

services:
  # Distributed Tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: modern-reservation-zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - QUERY_PORT=9411
    networks:
      - modern-reservation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database
  postgres:
    image: postgres:16
    container_name: modern-reservation-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - modern-reservation-network
    restart: unless-stopped

  # Database Management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: modern-reservation-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin-pgpass:/pgpass:ro
    networks:
      - modern-reservation-network
    restart: unless-stopped
    depends_on:
      - postgres

  # Cache
  redis:
    image: redis:7-alpine
    container_name: modern-reservation-redis
    ports:
      - "6379:6379"
    networks:
      - modern-reservation-network
    restart: unless-stopped

  # Service Discovery (Alternative to your Java Eureka)
  consul:
    image: consul:1.15
    container_name: modern-reservation-consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - modern-reservation-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  modern-reservation-network:
    driver: bridge
