# Application Services - Your Business Logic
# These are your actual microservices

version: '3.8'

services:
  # API Gateway
  gateway-service:
    build:
      context: ../../apps/backend/java-services/infrastructure/gateway-service
      dockerfile: Dockerfile
    container_name: modern-reservation-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - ZIPKIN_BASE_URL=http://zipkin:9411
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - zipkin
    networks:
      - modern-reservation-network
    restart: unless-stopped

  # Business Services
  reservation-engine:
    build:
      context: ../../apps/backend/java-services/business-services/reservation-engine
      dockerfile: Dockerfile
    container_name: modern-reservation-engine
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/modern_reservation_dev
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - ZIPKIN_BASE_URL=http://zipkin:9411
    depends_on:
      - postgres
      - redis
      - zipkin
    networks:
      - modern-reservation-network
    restart: unless-stopped

  payment-processor:
    build:
      context: ../../apps/backend/java-services/business-services/payment-processor
      dockerfile: Dockerfile
    container_name: modern-reservation-payments
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/modern_reservation_payments
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev_password123
      - ZIPKIN_BASE_URL=http://zipkin:9411
    depends_on:
      - postgres
      - zipkin
    networks:
      - modern-reservation-network
    restart: unless-stopped

networks:
  modern-reservation-network:
    external: true
