// Generated by @modern-reservation/port-manager
// DO NOT EDIT MANUALLY - Run: ./dev.sh config-generate

export const ServicePorts = {
  GUEST_PORTAL: 3000, // Guest Portal UI
  GUEST_PORTAL_DEV: 3001, // Guest Portal UI (Dev)
  ADMIN_PORTAL: 3010, // Admin Portal UI
  STAFF_PORTAL: 3020, // Staff Portal UI
  GATEWAY_SERVICE: 8080, // Spring Cloud Gateway - Main API Entry Point
  PGADMIN: 5050, // PgAdmin UI
  KAFKA_UI: 8090, // Kafka UI
  EUREKA_SERVER: 8761, // Eureka Service Discovery UI
  JAEGER: 16686, // Jaeger UI
  AUTH_SERVICE: 3100, // Authentication Service
  NOTIFICATION_SERVICE: 3110, // Notification Service
  WEBSOCKET_SERVICE: 3120, // WebSocket Service
  FILE_UPLOAD_SERVICE: 3130, // File Upload Service
  AUDIT_SERVICE: 3140, // Audit Service
  CHANNEL_MANAGER: 3150, // Channel Manager
  HOUSEKEEPING_SERVICE: 3160, // Housekeeping Service
  POSTGRES: 5432, // PostgreSQL Database
  POSTGRES_TEST: 5433, // PostgreSQL Test Database
  REDIS: 6379, // Redis Cache
  REDIS_CLUSTER: 6380, // Redis Cluster
  RESERVATION_ENGINE: 8100, // Reservation Engine Service
  AVAILABILITY_CALCULATOR: 8110, // Availability Calculator Service
  RATE_MANAGEMENT: 8120, // Rate Management Service
  PAYMENT_PROCESSOR: 8130, // Payment Processor Service
  ANALYTICS_ENGINE: 8140, // Analytics Engine Service
  TENANT_SERVICE: 8150, // Tenant Service
  CONFIG_SERVER: 8888, // Spring Cloud Config Server
  PROMETHEUS: 9090, // Prometheus Metrics
  GRAFANA: 3003, // Grafana Dashboard
  KAFKA: 9092, // Apache Kafka
  KAFKA_EXTERNAL: 29092, // Kafka External Access
  SCHEMA_REGISTRY: 8081, // Kafka Schema Registry
  ZOOKEEPER: 2181, // Zookeeper
  OTEL_COLLECTOR_GRPC: 4317, // OpenTelemetry Collector GRPC
  OTEL_COLLECTOR_HTTP: 4318 // OpenTelemetry Collector HTTP
} as const;

export const ServiceHosts = {
  GUEST_PORTAL: '0.0.0.0',
  GUEST_PORTAL_DEV: '0.0.0.0',
  ADMIN_PORTAL: '0.0.0.0',
  STAFF_PORTAL: '0.0.0.0',
  GATEWAY_SERVICE: '0.0.0.0',
  PGADMIN: '0.0.0.0',
  KAFKA_UI: '0.0.0.0',
  EUREKA_SERVER: '0.0.0.0',
  JAEGER: '0.0.0.0',
  AUTH_SERVICE: '127.0.0.1',
  NOTIFICATION_SERVICE: '127.0.0.1',
  WEBSOCKET_SERVICE: '127.0.0.1',
  FILE_UPLOAD_SERVICE: '127.0.0.1',
  AUDIT_SERVICE: '127.0.0.1',
  CHANNEL_MANAGER: '127.0.0.1',
  HOUSEKEEPING_SERVICE: '127.0.0.1',
  POSTGRES: '127.0.0.1',
  POSTGRES_TEST: '127.0.0.1',
  REDIS: '127.0.0.1',
  REDIS_CLUSTER: '127.0.0.1',
  RESERVATION_ENGINE: '127.0.0.1',
  AVAILABILITY_CALCULATOR: '127.0.0.1',
  RATE_MANAGEMENT: '127.0.0.1',
  PAYMENT_PROCESSOR: '127.0.0.1',
  ANALYTICS_ENGINE: '127.0.0.1',
  TENANT_SERVICE: '127.0.0.1',
  CONFIG_SERVER: '127.0.0.1',
  PROMETHEUS: '127.0.0.1',
  GRAFANA: '127.0.0.1',
  KAFKA: '127.0.0.1',
  KAFKA_EXTERNAL: '127.0.0.1',
  SCHEMA_REGISTRY: '127.0.0.1',
  ZOOKEEPER: '127.0.0.1',
  OTEL_COLLECTOR_GRPC: '127.0.0.1',
  OTEL_COLLECTOR_HTTP: '127.0.0.1'
} as const;

export const ServiceUrls = {
  GUEST_PORTAL: 'http://0.0.0.0:3000',
  GUEST_PORTAL_DEV: 'http://0.0.0.0:3001',
  ADMIN_PORTAL: 'http://0.0.0.0:3010',
  STAFF_PORTAL: 'http://0.0.0.0:3020',
  GATEWAY_SERVICE: 'http://0.0.0.0:8080',
  PGADMIN: 'http://0.0.0.0:5050',
  KAFKA_UI: 'http://0.0.0.0:8090',
  EUREKA_SERVER: 'http://0.0.0.0:8761',
  JAEGER: 'http://0.0.0.0:16686',
  AUTH_SERVICE: 'http://localhost:3100',
  NOTIFICATION_SERVICE: 'http://localhost:3110',
  WEBSOCKET_SERVICE: 'http://localhost:3120',
  FILE_UPLOAD_SERVICE: 'http://localhost:3130',
  AUDIT_SERVICE: 'http://localhost:3140',
  CHANNEL_MANAGER: 'http://localhost:3150',
  HOUSEKEEPING_SERVICE: 'http://localhost:3160',
  POSTGRES: 'tcp://localhost:5432',
  POSTGRES_TEST: 'tcp://localhost:5433',
  REDIS: 'tcp://localhost:6379',
  REDIS_CLUSTER: 'tcp://localhost:6380',
  RESERVATION_ENGINE: 'http://localhost:8100',
  AVAILABILITY_CALCULATOR: 'http://localhost:8110',
  RATE_MANAGEMENT: 'http://localhost:8120',
  PAYMENT_PROCESSOR: 'http://localhost:8130',
  ANALYTICS_ENGINE: 'http://localhost:8140',
  TENANT_SERVICE: 'http://localhost:8150',
  CONFIG_SERVER: 'http://localhost:8888',
  PROMETHEUS: 'http://localhost:9090',
  GRAFANA: 'http://localhost:3003',
  KAFKA: 'tcp://localhost:9092',
  KAFKA_EXTERNAL: 'tcp://localhost:29092',
  SCHEMA_REGISTRY: 'http://localhost:8081',
  ZOOKEEPER: 'tcp://localhost:2181',
  OTEL_COLLECTOR_GRPC: 'grpc://localhost:4317',
  OTEL_COLLECTOR_HTTP: 'http://localhost:4318'
} as const;
