theme: jekyll-theme-cayman
title: Modern Reservation System
description: Cloud-native microservices hotel reservation platform with event-driven architecture
show_downloads: true
github:
  repository_url: https://github.com/red2n/modern-reservation
  is_project_page: true

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-github-metadata

# Relative links configuration
relative_links:
  enabled: true
  collections: true

# Optional front matter
optional_front_matter:
  remove_originals: false

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Highlighter
highlighter: rouge

# Permalink
permalink: pretty
